### PR TITLE
Add support for the Markdown format that GPT is proficient with.

### PR DESCRIPTION
**Pull request by timwhitez**
Add support for the Markdown format that GPT is proficient with.

### CODE REVIEW

**Comment by NeoVertex1** [comment]
Could you provide results of gpt4o  outputs for this?

I think the fact you added python code like will make this prompt useless. Let know some good outputs before this is approved.

**Comment by shepherd333** [comment]
> Could you provide results of gpt4o outputs for this?
> 
> I think the fact you added python code like will make this prompt useless. Let know some good outputs before this is approved.

I don't think what is meant by this update is to change the output of the prompt, but rather make it such that it is more suitable for use in a developer's own app.  

Personally, I tried copy and pasting the original SuperPrompt into my code and ran into some issues with Python unable to handle math notations. I believe this is a solution to that. Have not tested it yet.

**Comment by timwhitez** [comment]
> Could you provide results of gpt4o outputs for this?
> 
> I think the fact you added python code like will make this prompt useless. Let know some good outputs before this is approved.

You are right, Python code isn't the best approach. I'm trying to use pseudocode to fix it

**Comment by timwhitez** [comment]
ask:
```
hey, think about the big bang theory a bit and do a historical_analysis for me, output your complete Thinking Process
```

answer:
```
**Action**: Conducting a historical analysis on the Big Bang Theory.

### Thinking Process

1. **Question (Concepts)**:
   - What is the historical context of the Big Bang Theory?
   - How has it evolved over time?

2. **Assert (Valid Conclusions)**:
   - The Big Bang Theory is the leading explanation for the origin of the universe.
   - It suggests the universe expanded from a hot, dense state.

3. **Refine (Through Recursive Iteration)**:
   - Consider key milestones and figures in its development.
   - Analyze how scientific advancements have shaped the theory.

### Expansion Path

- **1900-1920s**: 
  - **Albert Einstein**: Introduced General Relativity, providing a framework for cosmology.
  - **Edwin Hubble**: Discovered the universe is expanding, supporting the idea of an initial singularity.

- **1940s-1960s**:
  - **George Gamow**: Proposed the universe began with a hot, dense state.
  - **Arno Penzias and Robert Wilson**: Discovered Cosmic Microwave Background Radiation, providing evidence for the Big Bang.

- **1970s-Present**:
  - **Inflation Theory**: Proposed by Alan Guth, explaining uniformity of the universe.
  - **Advancements in technology**: Enhanced observations and simulations, refining the theory further.

### Recursive Exploration

- **Analyze Fundamental Concepts**:
  - The universe's expansion and cooling over time.
  - The role of quantum fluctuations in early universe conditions.

- **Deconstruct to Core Ideas**:
  - The interplay between general relativity and quantum mechanics.
  - The significance of observational evidence like redshift and cosmic background radiation.

### Verification

- **Logic Check**: Ensure the timeline and scientific principles are consistent.
- **Novelty Check**: Identify new insights gained from recent research and technology.

### Paradigm Shift

- **Integration of New Axioms**:
  - The concept of multiverse theories.
  - Exploration of dark matter and dark energy's role in cosmic evolution.

### Goal

- Unveil fundamental truths about the universe's origin through continuous scientific inquiry and technological advancement.

This historical analysis outlines the evolution of the Big Bang Theory and highlights key contributions and advancements that have shaped our understanding of the universe.
```

**Comment by timwhitez** [comment]
answer2 gpt-4o in coze platform Temperature:0.7 :
```
**Action**: Initiate historical_analysis of the Big Bang Theory with a complete breakdown of the Thinking Process.

## Thinking Process

### Step 1: Question (Concept)

**Concept**: The Big Bang Theory

- The Big Bang Theory is a scientific explanation for the origin of the universe, suggesting it began from an extremely hot and dense point approximately 13.8 billion years ago and has been expanding ever since.

### Step 2: Assert (Valid Conclusions)

**Assertions**:

1. **Historical Context**:
   - **Pre-20th Century**: Prevailing cosmological models were mostly static. The concept of an expanding universe was not widely considered.
   - **Early 20th Century**: Observational advancements and theoretical frameworks began to challenge the static universe model.

2. **Key Figures**:
   - **Albert Einstein (1915)**: General Theory of Relativity, which provided a new framework for understanding gravity and the dynamics of the universe.
   - **Georges Lemaître (1927)**: Proposed the idea of an expanding universe, suggesting it began from a "primeval atom."
   - **Edwin Hubble (1929)**: Provided observational evidence for the expanding universe through redshift measurements of distant galaxies.

3. **Development of the Theory**:
   - **1940s**: George Gamow and colleagues developed the idea of primordial nucleosynthesis, suggesting that elements were forged in the early universe.
   - **1960s**: Discovery of Cosmic Microwave Background Radiation (CMB) by Arno Penzias and Robert Wilson provided strong evidence for the Big Bang Theory.
   - **Late 20th Century**: Improved observations and theoretical refinements solidified the Big Bang Theory as the leading cosmological model.

### Step 3: Refine (Through Recursive Iteration)

**Refinements**:

- **Inflationary Theory (1980s)**: Alan Guth proposed the inflationary model to address issues like the horizon problem and the flatness problem in the standard Big Bang model.
- **Dark Matter and Dark Energy (Late 20th to Early 21st Century)**:
  - **Dark Matter**: Observations suggested that most of the universe's mass is in the form of dark matter, influencing the formation and behavior of galaxies.
  - **Dark Energy**: Discovery of the accelerated expansion of the universe, attributed to dark energy, further refined the Big Bang model.

### Step 4: Expansion Path

- **0**: Initial singularity (Big Bang)
- **[0,1]**: Formation of elementary particles and nuclei
- **[0,∞)**: Expansion and cooling of the universe
- **ℝ**: Formation of galaxies, stars, and planetary systems
- **ℂ**: Emergence of complex structures and life
- **𝕌**: Exploration of the universe's ultimate fate and higher-dimensional theories

### Step 5: Recursive Exploration

**Code**:
```pseudo
define explore(Big_Bang_Theory):
    if is_fundamental(Big_Bang_Theory):
        return analyze_fundamental(Big_Bang_Theory)
    else:
        return explore(deconstruct(Big_Bang_Theory_to_core))
```

### Step 6: Verification

- **Logic Check**: The Big Bang Theory is internally consistent with current cosmological observations.
- **Novelty Check**: Continual advancements in technology and theory lead to novel insights and refinements.

### Final Historical Analysis

**Historical Analysis**:

- The Big Bang Theory has evolved significantly from its inception in the early 20th century to the present day.
- Key contributions from scientists like Einstein, Lemaître, Hubble, and Guth have shaped the theory.
- Observational evidence such as the redshift of galaxies, CMB, and the discovery of dark matter and dark energy have solidified and refined the theory.
- The theory continues to evolve, integrating new discoveries and addressing unresolved questions about the universe's origin, structure, and fate.

**Conclusion**:

The Big Bang Theory remains a cornerstone of modern cosmology, providing a comprehensive framework for understanding the universe's origin and evolution. It exemplifies the dynamic nature of scientific theories, which are continually refined through observation and theoretical advancements.
```

**Comment by NeoVertex1** [comment]
Good job 🫡

**Pull request merged**
